name: slack_notification

on:
  workflow_dispatch:

jobs:
  slackjob:
    runs-on: ubuntu-latest
    env: 
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    steps:

    - name: PrintHello
      run: echo "Hello World"

    - name: Slack Notification
      uses: act10ns/slack@v2.0.0
      with:
        status: ${{ job.status }}
        steps: ${{ toJson(steps) }}
        chanel: '#test'
      if: always()
     
